# Generated by Django 5.0.2 on 2024-02-22 18:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name_plural": "Order"},
        ),
        migrations.AlterModelOptions(
            name="stock",
            options={"verbose_name_plural": "Stock"},
        ),
    ]
