# Generated by Django 5.0.1 on 2024-03-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="contact",
            field=models.IntegerField(null=True),
        ),
    ]
