# Generated by Django 5.0.1 on 2024-03-01 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_alter_profile_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name_plural": "Profile"},
        ),
        migrations.AlterField(
            model_name="profile",
            name="orders",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.order"
            ),
        ),
    ]
