# Generated by Django 5.0.1 on 2024-03-04 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_alter_profile_options_alter_profile_orders"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
