# Generated by Django 5.0.2 on 2024-03-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("released", "Released"),
                    ("pending", "Pending"),
                    ("returned", "Returned"),
                    ("approved", "Approved"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
