# Generated by Django 5.0.2 on 2024-03-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0011_alter_stock_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="stock",
            new_name="item_name",
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("released", "Released"),
                    ("pending", "Pending"),
                    ("returned", "Returned"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
