# Generated by Django 5.0.2 on 2024-03-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0012_rename_stock_order_item_name_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="returned_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
