# Generated by Django 5.0.2 on 2024-03-08 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0013_order_returned_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="TotalStock",
            fields=[
                (
                    "stock",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="inventory.stock",
                    ),
                ),
                ("total_quantity", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
