# Generated by Django 5.0.2 on 2024-03-08 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0014_totalstock"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TotalStock",
        ),
    ]
