# Generated by Django 5.0.2 on 2024-03-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0015_delete_totalstock"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="released_by",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="returned_to",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
