# Generated by Django 5.0.2 on 2024-03-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0016_order_released_by_order_returned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="in_stock",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
