# Generated by Django 5.0.2 on 2024-03-10 12:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0017_stock_in_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="in_stock",
        ),
    ]
