# Generated by Django 5.0.2 on 2024-05-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0018_remove_stock_in_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="intended_date_of_return",
            field=models.DateField(blank=True, null=True),
        ),
    ]
