# Generated by Django 5.0.2 on 2024-05-11 16:52

import django.utils.timezone
import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0019_order_intended_date_of_return"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now, monitor="status"
            ),
        ),
    ]
