# Generated by Django 5.0.2 on 2024-06-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0020_order_status_changed"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="issued_to",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
