# Generated by Django 5.0.2 on 2024-06-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0021_order_issued_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="issued_to",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
