# Generated by Django 5.0.2 on 2024-06-04 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0022_alter_order_issued_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="issued_to",
            field=models.CharField(
                max_length=200,
                null=True,
                verbose_name=django.db.models.deletion.CASCADE,
            ),
        ),
    ]
