# Generated by Django 5.0.2 on 2024-06-04 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0023_alter_order_issued_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="issued_to",
            field=models.CharField(
                max_length=200,
                null=models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL,
                ),
            ),
        ),
    ]
