# Generated by Django 5.0.2 on 2024-06-06 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0024_alter_order_issued_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="approved_by",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="issued_to",
            field=models.CharField(
                blank=models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL,
                ),
                max_length=200,
                null=True,
            ),
        ),
    ]
