# Generated by Django 5.0.2 on 2024-07-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0025_order_approved_by_alter_order_issued_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="request_description",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
